apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/bikram/Git/opencti-docker/.tools/kompose convert -f /Users/bikram/Git/opencti-docker/docker-compose.yml --out /Users/bikram/Git/opencti-docker/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: connector-silobreaker
  name: connector-silobreaker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connector-silobreaker
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/bikram/Git/opencti-docker/.tools/kompose convert -f /Users/bikram/Git/opencti-docker/docker-compose.yml --out /Users/bikram/Git/opencti-docker/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: connector-silobreaker
    spec:
      containers:
        - env:
            - name: CONNECTOR_DURATION_PERIOD
              value: PT60M
            - name: CONNECTOR_ID
              value: ${CONNECTOR_SILOBREAKER_ID}
            - name: CONNECTOR_LOG_LEVEL
              value: error
            - name: CONNECTOR_NAME
              value: Silobreaker Cyber Threat Intelligence
            - name: CONNECTOR_SCOPE
              value: silobreaker
            - name: OPENCTI_TOKEN
              value: ${OPENCTI_ADMIN_TOKEN}
            - name: OPENCTI_URL
              value: ${OPENCTI_INTERNAL_URL}${OPENCTI_BASE_PATH}
            - name: SILOBREAKER_API_KEY
              value: ${SILOBREAKER_API_KEY}
            - name: SILOBREAKER_API_SHARED
              value: ${SILOBREAKER_API_SHARED}
            - name: SILOBREAKER_API_URL
              value: https://api.silobreaker.com
            - name: SILOBREAKER_IMPORT_START_DATE
              value: "2026-02-01"
            - name: SILOBREAKER_LISTS
              value: 138809,96910,36592,55112,50774
          image: opencti/connector-silobreaker:${OPENCTI_VERSION}
          name: connector-silobreaker
      restartPolicy: Always