apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: connector-threatfox
  name: connector-threatfox
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connector-threatfox
  template:
    metadata:
      labels:
        io.kompose.service: connector-threatfox
    spec:
      containers:
        - env:
            - name: CONNECTOR_ID
              value: ${CONNECTOR_THREATFOX_ID}
            - name: CONNECTOR_LOG_LEVEL
              value: info
            - name: CONNECTOR_NAME
              value: ThreatFox
            - name: CONNECTOR_SCOPE
              value: threatfox
            - name: OPENCTI_TOKEN
              value: ${OPENCTI_ADMIN_TOKEN}
            - name: OPENCTI_URL
              value: ${OPENCTI_INTERNAL_URL}${OPENCTI_BASE_PATH}
            - name: THREATFOX_INTERVAL
              value: "${THREATFOX_INTERVAL}"
          image: opencti/connector-threatfox:${OPENCTI_VERSION}
          name: connector-threatfox
      restartPolicy: Always