apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/bikram/Git/opencti-docker/.tools/kompose convert -f /Users/bikram/Git/opencti-docker/docker-compose.yml --out /Users/bikram/Git/opencti-docker/k8s
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: connector-import-file-stix
  name: connector-import-file-stix
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: connector-import-file-stix
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/bikram/Git/opencti-docker/.tools/kompose convert -f /Users/bikram/Git/opencti-docker/docker-compose.yml --out /Users/bikram/Git/opencti-docker/k8s
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: connector-import-file-stix
    spec:
      containers:
        - env:
            - name: CONNECTOR_AUTO
              value: "false"
            - name: CONNECTOR_CONFIDENCE_LEVEL
              value: "15"
            - name: CONNECTOR_ID
              value: ${CONNECTOR_IMPORT_FILE_STIX_ID}
            - name: CONNECTOR_LOG_LEVEL
              value: info
            - name: CONNECTOR_NAME
              value: ImportFileStix
            - name: CONNECTOR_SCOPE
              value: application/json,text/xml
            - name: CONNECTOR_TYPE
              value: INTERNAL_IMPORT_FILE
            - name: CONNECTOR_VALIDATE_BEFORE_IMPORT
              value: "true"
            - name: OPENCTI_TOKEN
              value: ${OPENCTI_ADMIN_TOKEN}
            - name: OPENCTI_URL
              value: ${OPENCTI_INTERNAL_URL}${OPENCTI_BASE_PATH}
          image: opencti/connector-import-file-stix:${OPENCTI_VERSION}
          name: connector-import-file-stix
      restartPolicy: Always
