apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: opencti
  name: opencti
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    io.kompose.service: opencti